Repository awslabs/fhir-works-on-aws-routing, pull requests merged in 2021-06, with the labels that each got.

#91 refactor: remove usages of req.baseUrl
  src/app.ts
  src/router/routes/genericResourceRoute.ts
Labels: size/s

#93 chore(release): 5.4.2
  CHANGELOG.md
  package.json
Labels: documentation, size/s

#94 feat: pass tenantId to subcomponents. Allow tenant specific URLs
  src/app.ts
  src/operationDefinitions/USCoreDocRef/index.ts
  src/router/handlers/CrudHandlerInterface.ts
  src/router/handlers/exportHandler.ts
  src/router/handlers/resourceHandler.test.ts
  src/router/handlers/resourceHandler.ts
  src/router/handlers/rootHandler.ts
  src/router/middlewares/setServerUrl.test.ts
  src/router/middlewares/setServerUrl.ts
  src/router/middlewares/setTenantId.test.ts
  src/router/middlewares/setTenantId.ts
  src/router/routes/exportRoute.ts
  src/router/routes/exportRouteHelper.ts
  src/router/routes/genericResourceRoute.ts
  src/router/routes/rootRoute.ts
Labels: size/l

#97 feat: pass tenantId to bundle service
  src/router/bundle/bundleHandler.ts
  src/router/bundle/bundleHandlerInterface.ts
  src/router/routes/rootRoute.ts
Labels: size/s
