Repository awslabs/fhir-works-on-aws-routing, pull requests merged in 2021-05, with the labels that each got.

#74 fix: handle POST bundle with no fullUrl and relative refs
  src/router/bundle/bundleParser.test.ts
  src/router/bundle/bundleParser.ts
Labels: size/s

#75 fix: bad substitution in absolute URL refs that match the server url
  src/regExpressions.ts
  src/router/bundle/bundleParser.test.ts
  src/router/bundle/bundleParser.ts
Labels: size/s

#76 chore(release): 5.2.1
  CHANGELOG.md
  package.json
Labels: size/s

#77 refactor: consolidate search logic inside ResourceHandler
  src/router/handlers/CrudHandlerInterface.ts
  src/router/handlers/resourceHandler.test.ts
  src/router/handlers/resourceHandler.ts
  src/router/routes/genericResourceRoute.ts
Labels: size/s

#78 feat: add US Core $docref implementation
  package.json
  src/operationDefinitions/USCoreDocRef/convertDocRefParamsToSearchParams.ts
  src/operationDefinitions/USCoreDocRef/docRefParamsToSearchParams.test.ts
  src/operationDefinitions/USCoreDocRef/index.ts
  src/operationDefinitions/USCoreDocRef/parseParams.test.ts
  src/operationDefinitions/USCoreDocRef/parseParams.ts
  src/operationDefinitions/types.ts
  yarn.lock
Labels: size/l

#81 feat: Add winston logger
  package.json
  sampleData/r4FhirConfigGeneric.ts
  sampleData/r4FhirConfigNoGeneric.ts
  sampleData/r4FhirConfigWithExclusions.ts
  sampleData/stu3FhirConfigWithExclusions.ts
  src/loggerBuilder.ts
  src/router/validation/hapiFhirLambdaValidator.ts
  yarn.lock
Labels: size/m

#84 chore(release): 5.3.0
  CHANGELOG.md
  package.json
Labels: size/xs

#83 feat: enable $docref based on the compiled IGs
  src/app.ts
  src/configHandler.ts
  src/implementationGuides/index.test.ts
  src/implementationGuides/index.ts
  src/operationDefinitions/OperationDefinitionRegistry.test.ts
  src/operationDefinitions/OperationDefinitionRegistry.ts
  src/operationDefinitions/USCoreDocRef/index.ts
  src/operationDefinitions/USCoreDocRef/parseParams.ts
  src/operationDefinitions/index.ts
  src/operationDefinitions/types.ts
  src/registry/index.ts
Labels: size/m

#85 feat: add docref to capability statement
  src/app.ts
  src/operationDefinitions/OperationDefinitionRegistry.test.ts
  src/operationDefinitions/OperationDefinitionRegistry.ts
  src/operationDefinitions/USCoreDocRef/index.ts
  src/operationDefinitions/types.ts
  src/router/metadata/cap.rest.resource.template.ts
  src/router/metadata/metadataHandler.test.ts
  src/router/metadata/metadataHandler.ts
  src/router/routes/metadataRoute.ts
  yarn.lock
Labels: size/m

#86 feat: add $docref operation
  package.json
  src/app.ts
  src/configHandler.ts
  src/implementationGuides/index.test.ts
  src/implementationGuides/index.ts
  src/operationDefinitions/OperationDefinitionRegistry.test.ts
  src/operationDefinitions/OperationDefinitionRegistry.ts
  src/operationDefinitions/USCoreDocRef/convertDocRefParamsToSearchParams.ts
  src/operationDefinitions/USCoreDocRef/docRefParamsToSearchParams.test.ts
  src/operationDefinitions/USCoreDocRef/index.ts
  src/operationDefinitions/USCoreDocRef/parseParams.test.ts
  src/operationDefinitions/USCoreDocRef/parseParams.ts
  src/operationDefinitions/index.ts
  src/operationDefinitions/types.ts
  src/registry/index.ts
  src/router/metadata/cap.rest.resource.template.ts
  src/router/metadata/metadataHandler.test.ts
  src/router/metadata/metadataHandler.ts
  src/router/routes/metadataRoute.ts
  yarn.lock
Labels: size/xl

#87 chore(release): 5.4.0
  CHANGELOG.md
  package.json
Labels: size/xs

#82 chore: adding GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/miscellaneous.md
Labels: size/s

#89 fix: remove informational HTTP header
  src/app.ts
Labels: bug, size/xs
