Repository awslabs/fhir-works-on-aws-routing, pull requests merged in 2021-09, with the labels that each got.

#124 fix: properly emit throttle error
  src/router/routes/errorHandling.ts
Labels: size/xs

#125 feat: add group export operation to capability statement
  src/router/metadata/cap.rest.template.ts
  src/router/metadata/metadataHandler.test.ts
Labels: size/s

#128 chore(release): 6.1.1
  CHANGELOG.md
  package.json
Labels: size/xs

#129 chore: normalize all the line endings
  .github/PULL_REQUEST_TEMPLATE.md
  .github/no-response.yaml
  .npmignore
  .npmrc
  THIRD-PARTY
  sampleData/r4FhirConfigGeneric.ts
  sampleData/r4FhirConfigNoGeneric.ts
  src/configHandler.ts
  src/constants.ts
  src/index.ts
  src/regExpressions.test.ts
  src/regExpressions.ts
  src/router/bundle/bundleGenerator.ts
  src/router/bundle/bundleHandler.test.ts
  src/router/bundle/bundleHandler.ts
  src/router/bundle/bundleHandlerInterface.ts
  src/router/bundle/bundleParser.test.ts
  src/router/bundle/bundleParser.ts
  src/router/handlers/CrudHandlerInterface.ts
  src/router/handlers/resourceHandler.test.ts
  src/router/handlers/resourceHandler.ts
  src/router/handlers/rootHandler.ts
  src/router/metadata/cap.rest.resource.template.ts
  src/router/metadata/cap.rest.template.ts
  src/router/metadata/cap.template.ts
  src/router/metadata/metadataHandler.test.ts
  src/router/metadata/metadataHandler.ts
  src/router/operationsGenerator.ts
  src/router/routes/metadataRoute.ts
  src/router/routes/rootRoute.ts
  src/router/routes/routeHelper.ts
Labels: size/xl

#133 chore(release): 6.1.2
  CHANGELOG.md
  package.json
Labels: size/xs

#134 chore: resolve transitive dependency on set-value package
  package.json
  yarn.lock
Labels: size/s
