Repository awslabs/fhir-works-on-aws-routing, pull requests merged in 2021-11, with the labels that each got.

#142 chore: add git secrets scan
  .github/workflows/unit-test.yaml
Labels: size/s

#143 chore: update CODEOWNERS
  CODEOWNERS
Labels: size/xs

#144 chore: release automation
  .github/workflows/release-pr.yml
  .github/workflows/tag-and-publish.yml
  package.json
  yarn.lock
Labels: size/l
