Repository awslabs/fhir-works-on-aws-routing, pull requests merged in 2021-03, with the labels that each got.

#63 feat: add HAPI FHIR Lambda Validator
  package.json
  src/AWS.ts
  src/offlineEnvVariables.ts
  src/router/validation/hapiFhirLambdaValidator.test.ts
  src/router/validation/hapiFhirLambdaValidator.ts
  yarn.lock
Labels: size/m

#65 fix: fix stu3 schema for Bundle & AllergyIntolerance
  src/router/validation/jsonSchemaValidator.test.ts
  src/router/validation/schemas/fhir.schema.v3.json
Labels: size/s

#66 feat: add Implementation Guides support
  package.json
  src/AWS.ts
  src/app.ts
  src/implementationGuides/index.test.ts
  src/implementationGuides/index.ts
  src/offlineEnvVariables.ts
  src/registry/ResourceCapabilityInterface.ts
  src/registry/index.test.ts
  src/registry/index.ts
  src/router/metadata/cap.rest.resource.template.ts
  src/router/metadata/metadataHandler.test.ts
  src/router/metadata/metadataHandler.ts
  src/router/routes/metadataRoute.ts
  src/router/validation/hapiFhirLambdaValidator.test.ts
  src/router/validation/hapiFhirLambdaValidator.ts
  yarn.lock
Labels: size/l

#67 chore(release): 5.1.0
  CHANGELOG.md
  package.json
Labels: size/s

#68 chore: Add customer user agent
  src/AWS.ts
Labels: size/xs

#69 chore(release): 5.1.1
  CHANGELOG.md
  package.json
Labels: size/xs
