Repository awslabs/fhir-works-on-aws-routing, pull requests merged in 2021-08, with the labels that each got.

#107 feat: Group export map additional parameters needed
  src/app.ts
  src/router/bundle/bundleHandler.test.ts
  src/router/routes/exportRoute.ts
  src/router/routes/exportRouteHelper.ts
Labels: size/m

#109 fix: add routing for 409 errors
  package.json
  src/router/routes/errorHandling.ts
Labels: size/xs

#110 chore(release): 5.4.4
  CHANGELOG.md
  package.json
Labels: size/s

#112 fix: Lint fix
  src/router/bundle/bundleHandler.test.ts
Labels: size/xs

#113 chore: dependency bump
  package.json
  yarn.lock
Labels: size/s

#115 chore: Dependency fix
  package.json
  yarn.lock
Labels: size/s

#117 fix: Handle 401 correctly in OperationOutcomes
  src/router/routes/errorHandling.ts
Labels: size/xs

#116 feat!: add support for multi-tenancy and group export
  package.json
  src/app.ts
  src/operationDefinitions/USCoreDocRef/index.ts
  src/router/bundle/bundleHandler.test.ts
  src/router/bundle/bundleHandler.ts
  src/router/bundle/bundleHandlerInterface.ts
  src/router/handlers/CrudHandlerInterface.ts
  src/router/handlers/exportHandler.ts
  src/router/handlers/resourceHandler.test.ts
  src/router/handlers/resourceHandler.ts
  src/router/handlers/rootHandler.ts
  src/router/middlewares/setServerUrl.test.ts
  src/router/middlewares/setServerUrl.ts
  src/router/middlewares/setTenantId.test.ts
  src/router/middlewares/setTenantId.ts
  src/router/routes/exportRoute.ts
  src/router/routes/exportRouteHelper.test.ts
  src/router/routes/exportRouteHelper.ts
  src/router/routes/genericResourceRoute.ts
  src/router/routes/rootRoute.ts
  yarn.lock
Labels: size/l

#118 chore(release): 6.0.0
  CHANGELOG.md
  package.json
Labels: size/s

#119 fix: pass serverUrl to bundle auth request
  package.json
  src/router/bundle/bundleHandler.ts
  yarn.lock
Labels: size/s

#120 chore(release): 6.0.1
  CHANGELOG.md
  package.json
Labels: size/xs
