Repository awslabs/fhir-works-on-aws-routing, pull requests merged in 2022-03, with the labels that each got.

#156 feat: add Subscription validator
  package.json
  src/router/__mocks__/dynamoDbDataService.ts
  src/router/__mocks__/elasticSearchService.ts
  src/router/bundle/bundleHandler.ts
  src/router/handlers/resourceHandler.test.ts
  src/router/handlers/resourceHandler.ts
  src/router/validation/hapiFhirLambdaValidator.ts
  src/router/validation/jsonSchemaValidator.ts
  src/router/validation/subscriptionSchema.json
  src/router/validation/subscriptionValidator.test.ts
  src/router/validation/subscriptionValidator.ts
  src/router/validation/validationUtilities.ts
  yarn.lock
Labels: size/l

#159 chore(release): 6.4.0
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr

#160 fix: fix content type for .well-known/smart-configuration
  src/router/routes/wellKnownUriRoute.ts
Labels: size/xs

#161 chore(release): 6.4.1
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr
