Repository awslabs/fhir-works-on-aws-routing, pull requests merged in 2023-01, with the labels that each got.

#187 chore: update documentation TLS
  README.md
Labels: size/xs

#188 chore: update json5 version
  package.json
  yarn.lock
Labels: size/s

#189 docs: link best practices for api gateway
  README.md
Labels: size/xs

#190 Fix add 405 error
  src/router/routes/errorHandling.ts
Labels: size/xs

#191 chore: add bad request error handling
  src/router/routes/errorHandling.ts
Labels: size/xs

#193 fix: add optional input validation
  package.json
  src/router/handlers/resourceHandler.test.ts
  src/router/handlers/resourceHandler.ts
  src/router/handlers/utils.ts
  src/router/validation/validationUtilities.ts
  yarn.lock
Labels: size/m

#195 chore(release): 6.6.2
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr

#196 perf: improve regex performance with length limitation
  src/constants.ts
  src/regExpressions.test.ts
  src/regExpressions.ts
  src/router/bundle/bundleParser.test.ts
  src/router/bundle/bundleParser.ts
Labels: size/m
